---
- import_tasks: CentOS-7.yml
  when:
    - ansible_facts.distribution == 'CentOS'
    - ansible_facts.distribution_major_version == '7'

- import_tasks: lxd-common.yml
  when:
    - ansible_facts.distribution == 'CentOS'
    - ansible_facts.distribution_major_version == '7'
